// ─────────────────────────────────────────────────────────
// .NET Templates — Clean & Layered Architecture
// (ASP.NET Core 8 + C#)
// ─────────────────────────────────────────────────────────

import { TemplateManifest } from '../types';

const solutionFile = {
  path: '<%= projectName %>.sln',
  content: `
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
# Generated by ArchForge
`,
};

const sharedFiles = [solutionFile];

// ── Clean Architecture ──────────────────────────────────

export const dotnetCleanManifest: TemplateManifest = {
  stack: 'dotnet',
  architecture: 'clean',
  files: [
    ...sharedFiles,
    // Domain project
    {
      path: 'src/Domain/<%= projectName %>.Domain.csproj',
      content: `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
`,
    },
    {
      path: 'src/Domain/Entities/User.cs',
      content: `namespace <%= projectName %>.Domain.Entities;

/// <summary>
/// Domain Entity: User
/// Pure business object — no framework dependencies.
/// </summary>
public class User
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}
`,
    },
    {
      path: 'src/Domain/Interfaces/IUserRepository.cs',
      content: `using <%= projectName %>.Domain.Entities;

namespace <%= projectName %>.Domain.Interfaces;

/// <summary>
/// Repository interface — implementations live in Infrastructure.
/// </summary>
public interface IUserRepository
{
    Task<User?> GetByIdAsync(Guid id);
    Task<IEnumerable<User>> GetAllAsync();
    Task<User> CreateAsync(User user);
    Task DeleteAsync(Guid id);
}
`,
    },
    // Application project
    {
      path: 'src/Application/<%= projectName %>.Application.csproj',
      content: `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/<%= projectName %>.Domain.csproj" />
  </ItemGroup>
</Project>
`,
    },
    {
      path: 'src/Application/UseCases/GetUsersUseCase.cs',
      content: `using <%= projectName %>.Domain.Entities;
using <%= projectName %>.Domain.Interfaces;

namespace <%= projectName %>.Application.UseCases;

/// <summary>
/// Use Case: Get all users.
/// </summary>
public class GetUsersUseCase
{
    private readonly IUserRepository _userRepository;

    public GetUsersUseCase(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    public async Task<IEnumerable<User>> ExecuteAsync()
    {
        return await _userRepository.GetAllAsync();
    }
}
`,
    },
    {
      path: 'src/Application/UseCases/CreateUserUseCase.cs',
      content: `using <%= projectName %>.Domain.Entities;
using <%= projectName %>.Domain.Interfaces;

namespace <%= projectName %>.Application.UseCases;

/// <summary>
/// Use Case: Create a new user.
/// </summary>
public class CreateUserUseCase
{
    private readonly IUserRepository _userRepository;

    public CreateUserUseCase(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    public async Task<User> ExecuteAsync(string name, string email)
    {
        var user = new User
        {
            Id = Guid.NewGuid(),
            Name = name,
            Email = email,
            CreatedAt = DateTime.UtcNow
        };
        return await _userRepository.CreateAsync(user);
    }
}
`,
    },
    // Infrastructure project
    {
      path: 'src/Infrastructure/<%= projectName %>.Infrastructure.csproj',
      content: `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Application/<%= projectName %>.Application.csproj" />
  </ItemGroup>
<% if (database === 'postgresql') { %>  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>
<% } else if (database === 'mysql') { %>  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>
<% } %>
</Project>
`,
    },
    {
      path: 'src/Infrastructure/Repositories/InMemoryUserRepository.cs',
      content: `using System.Collections.Concurrent;
using <%= projectName %>.Domain.Entities;
using <%= projectName %>.Domain.Interfaces;

namespace <%= projectName %>.Infrastructure.Repositories;

/// <summary>
/// In-memory implementation. Replace with EF Core for production.
/// </summary>
public class InMemoryUserRepository : IUserRepository
{
    private readonly ConcurrentDictionary<Guid, User> _store = new();

    public Task<User?> GetByIdAsync(Guid id)
    {
        _store.TryGetValue(id, out var user);
        return Task.FromResult(user);
    }

    public Task<IEnumerable<User>> GetAllAsync()
    {
        return Task.FromResult<IEnumerable<User>>(_store.Values);
    }

    public Task<User> CreateAsync(User user)
    {
        _store[user.Id] = user;
        return Task.FromResult(user);
    }

    public Task DeleteAsync(Guid id)
    {
        _store.TryRemove(id, out _);
        return Task.CompletedTask;
    }
}
`,
    },
    // Presentation (Web API) project
    {
      path: 'src/WebApi/<%= projectName %>.WebApi.csproj',
      content: `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Infrastructure/<%= projectName %>.Infrastructure.csproj" />
  </ItemGroup>
<% if (auth === 'jwt') { %>  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>
<% } %>
</Project>
`,
    },
    {
      path: 'src/WebApi/Program.cs',
      content: `using <%= projectName %>.Application.UseCases;
using <%= projectName %>.Domain.Interfaces;
using <%= projectName %>.Infrastructure.Repositories;

var builder = WebApplication.CreateBuilder(args);

// Register services
builder.Services.AddSingleton<IUserRepository, InMemoryUserRepository>();
builder.Services.AddTransient<GetUsersUseCase>();
builder.Services.AddTransient<CreateUserUseCase>();
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
<% if (auth !== 'none') { %>app.UseAuthentication();
<% } %>app.UseAuthorization();
app.MapControllers();
app.Run();
`,
    },
    {
      path: 'src/WebApi/Controllers/UsersController.cs',
      content: `using <%= projectName %>.Application.UseCases;
using <%= projectName %>.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace <%= projectName %>.WebApi.Controllers;

[ApiController]
[Route("api/[controller]")]
public class UsersController : ControllerBase
{
    private readonly GetUsersUseCase _getUsersUseCase;
    private readonly CreateUserUseCase _createUserUseCase;

    public UsersController(GetUsersUseCase getUsersUseCase, CreateUserUseCase createUserUseCase)
    {
        _getUsersUseCase = getUsersUseCase;
        _createUserUseCase = createUserUseCase;
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var users = await _getUsersUseCase.ExecuteAsync();
        return Ok(users);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateUserRequest request)
    {
        var user = await _createUserUseCase.ExecuteAsync(request.Name, request.Email);
        return Ok(user);
    }
}

public record CreateUserRequest(string Name, string Email);
`,
    },
    {
      path: 'src/WebApi/appsettings.json',
      content: `{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
`,
    },
  ],
  postMessages: [
    'Run `dotnet restore` to install dependencies',
    'Run `dotnet run --project src/WebApi` to start the API',
    'Architecture: Clean Architecture (Domain → Application → Infrastructure → Presentation)',
  ],
};

// ── Layered Architecture ────────────────────────────────

export const dotnetLayeredManifest: TemplateManifest = {
  stack: 'dotnet',
  architecture: 'layered',
  files: [
    ...sharedFiles,
    {
      path: 'src/<%= projectName %>/<%= projectName %>.csproj',
      content: `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<% if (database === 'postgresql') { %>  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>
<% } else if (database === 'mysql') { %>  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>
<% } %>
</Project>
`,
    },
    {
      path: 'src/<%= projectName %>/Program.cs',
      content: `var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();
`,
    },
    {
      path: 'src/<%= projectName %>/Models/User.cs',
      content: `namespace <%= projectName %>.Models;

public class User
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}
`,
    },
    {
      path: 'src/<%= projectName %>/Services/UserService.cs',
      content: `using <%= projectName %>.Models;

namespace <%= projectName %>.Services;

public class UserService
{
    private readonly List<User> _users = new();

    public IEnumerable<User> GetAll() => _users;

    public User Create(string name, string email)
    {
        var user = new User
        {
            Id = Guid.NewGuid(),
            Name = name,
            Email = email,
            CreatedAt = DateTime.UtcNow
        };
        _users.Add(user);
        return user;
    }
}
`,
    },
    {
      path: 'src/<%= projectName %>/Controllers/UsersController.cs',
      content: `using <%= projectName %>.Services;
using Microsoft.AspNetCore.Mvc;

namespace <%= projectName %>.Controllers;

[ApiController]
[Route("api/[controller]")]
public class UsersController : ControllerBase
{
    private readonly UserService _userService;

    public UsersController(UserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public IActionResult GetAll() => Ok(_userService.GetAll());
}
`,
    },
  ],
  postMessages: [
    'Run `dotnet restore` to install dependencies',
    'Run `dotnet run --project src/<%= projectName %>` to start the API',
    'Architecture: Layered (Controllers → Services → Models)',
  ],
};
