// ─────────────────────────────────────────────────────────
// Flutter Templates — Clean, Layered
// Dart + Flutter 3 + Riverpod
// ─────────────────────────────────────────────────────────

import { TemplateManifest } from '../types';

// ── Shared files ────────────────────────────────────────

const pubspecYaml = {
  path: 'pubspec.yaml',
  content: `name: <%= projectName %>
description: Generated by ArchForge
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
`,
};

const analysisOptions = {
  path: 'analysis_options.yaml',
  content: `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
`,
};

const mainDart = {
  path: 'lib/main.dart',
  content: `import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';

void main() {
  runApp(const ProviderScope(child: App()));
}
`,
};

const appDart = {
  path: 'lib/app.dart',
  content: `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'router.dart';

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: '<%= projectName %>',
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
      ),
      routerConfig: router,
    );
  }
}
`,
};

const gitignore = {
  path: '.gitignore',
  content: `build/
.dart_tool/
.packages
.pub/
*.g.dart
`,
};

// ── Clean Architecture ──────────────────────────────────

export const flutterCleanManifest: TemplateManifest = {
  stack: 'flutter',
  architecture: 'clean',
  files: [
    pubspecYaml,
    analysisOptions,
    mainDart,
    appDart,
    gitignore,
    {
      path: 'lib/router.dart',
      content: `import 'package:go_router/go_router.dart';
import 'presentation/pages/user_list_page.dart';

final router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const UserListPage(),
    ),
  ],
);
`,
    },
    // ── Domain layer
    {
      path: 'lib/domain/entities/user.dart',
      content: `class User {
  final String id;
  final String name;
  final String email;

  const User({required this.id, required this.name, required this.email});
}
`,
    },
    {
      path: 'lib/domain/repositories/user_repository.dart',
      content: `import '../entities/user.dart';

abstract class UserRepository {
  Future<List<User>> getAll();
  Future<User> getById(String id);
}
`,
    },
    {
      path: 'lib/domain/usecases/get_users.dart',
      content: `import '../entities/user.dart';
import '../repositories/user_repository.dart';

class GetUsers {
  final UserRepository repository;

  GetUsers(this.repository);

  Future<List<User>> call() => repository.getAll();
}
`,
    },
    // ── Data layer
    {
      path: 'lib/data/models/user_model.dart',
      content: `import '../../domain/entities/user.dart';

class UserModel extends User {
  const UserModel({
    required super.id,
    required super.name,
    required super.email,
  });

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['id'].toString(),
      name: json['name'] as String,
      email: json['email'] as String,
    );
  }
}
`,
    },
    {
      path: 'lib/data/datasources/user_remote_datasource.dart',
      content: `import 'package:dio/dio.dart';
import '../models/user_model.dart';

class UserRemoteDatasource {
  final Dio dio;

  UserRemoteDatasource(this.dio);

  Future<List<UserModel>> getUsers() async {
    final response = await dio.get('https://jsonplaceholder.typicode.com/users');
    return (response.data as List)
        .map((json) => UserModel.fromJson(json))
        .toList();
  }
}
`,
    },
    {
      path: 'lib/data/repositories/user_repository_impl.dart',
      content: `import '../../domain/entities/user.dart';
import '../../domain/repositories/user_repository.dart';
import '../datasources/user_remote_datasource.dart';

class UserRepositoryImpl implements UserRepository {
  final UserRemoteDatasource datasource;

  UserRepositoryImpl(this.datasource);

  @override
  Future<List<User>> getAll() => datasource.getUsers();

  @override
  Future<User> getById(String id) async {
    final users = await datasource.getUsers();
    return users.firstWhere((u) => u.id == id);
  }
}
`,
    },
    // ── Presentation layer
    {
      path: 'lib/presentation/providers/user_providers.dart',
      content: `import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:dio/dio.dart';
import '../../domain/entities/user.dart';
import '../../domain/usecases/get_users.dart';
import '../../data/datasources/user_remote_datasource.dart';
import '../../data/repositories/user_repository_impl.dart';

final dioProvider = Provider((ref) => Dio());

final userRepositoryProvider = Provider((ref) {
  final dio = ref.read(dioProvider);
  return UserRepositoryImpl(UserRemoteDatasource(dio));
});

final getUsersProvider = FutureProvider<List<User>>((ref) {
  final repo = ref.read(userRepositoryProvider);
  return GetUsers(repo).call();
});
`,
    },
    {
      path: 'lib/presentation/pages/user_list_page.dart',
      content: `import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/user_providers.dart';

class UserListPage extends ConsumerWidget {
  const UserListPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final usersAsync = ref.watch(getUsersProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('<%= projectName %>')),
      body: usersAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, _) => Center(child: Text('Error: \$err')),
        data: (users) => ListView.builder(
          itemCount: users.length,
          itemBuilder: (context, index) {
            final user = users[index];
            return ListTile(
              title: Text(user.name),
              subtitle: Text(user.email),
            );
          },
        ),
      ),
    );
  }
}
`,
    },
  ],
  postMessages: [
    'Run `flutter pub get`',
    'Run `flutter run` to launch the app',
    'Architecture: Clean (Domain → Data → Presentation)',
  ],
};

// ── Layered Architecture ────────────────────────────────

export const flutterLayeredManifest: TemplateManifest = {
  stack: 'flutter',
  architecture: 'layered',
  files: [
    pubspecYaml,
    analysisOptions,
    mainDart,
    appDart,
    gitignore,
    {
      path: 'lib/router.dart',
      content: `import 'package:go_router/go_router.dart';
import 'ui/pages/user_list_page.dart';

final router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const UserListPage(),
    ),
  ],
);
`,
    },
    // ── Models layer
    {
      path: 'lib/models/user.dart',
      content: `class User {
  final String id;
  final String name;
  final String email;

  const User({required this.id, required this.name, required this.email});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'].toString(),
      name: json['name'] as String,
      email: json['email'] as String,
    );
  }
}
`,
    },
    // ── Services layer
    {
      path: 'lib/services/user_service.dart',
      content: `import 'package:dio/dio.dart';
import '../models/user.dart';

class UserService {
  final Dio _dio;

  UserService(this._dio);

  Future<List<User>> getUsers() async {
    final response = await _dio.get('https://jsonplaceholder.typicode.com/users');
    return (response.data as List).map((json) => User.fromJson(json)).toList();
  }
}
`,
    },
    // ── Providers
    {
      path: 'lib/providers/user_providers.dart',
      content: `import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:dio/dio.dart';
import '../models/user.dart';
import '../services/user_service.dart';

final dioProvider = Provider((ref) => Dio());

final userServiceProvider = Provider((ref) {
  return UserService(ref.read(dioProvider));
});

final usersProvider = FutureProvider<List<User>>((ref) {
  return ref.read(userServiceProvider).getUsers();
});
`,
    },
    // ── UI layer
    {
      path: 'lib/ui/pages/user_list_page.dart',
      content: `import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../providers/user_providers.dart';

class UserListPage extends ConsumerWidget {
  const UserListPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final usersAsync = ref.watch(usersProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('<%= projectName %>')),
      body: usersAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, _) => Center(child: Text('Error: \$err')),
        data: (users) => ListView.builder(
          itemCount: users.length,
          itemBuilder: (context, index) {
            final user = users[index];
            return ListTile(
              title: Text(user.name),
              subtitle: Text(user.email),
            );
          },
        ),
      ),
    );
  }
}
`,
    },
    {
      path: 'lib/ui/widgets/app_button.dart',
      content: `import 'package:flutter/material.dart';

class AppButton extends StatelessWidget {
  final String label;
  final VoidCallback onPressed;

  const AppButton({super.key, required this.label, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: onPressed,
      child: Text(label),
    );
  }
}
`,
    },
  ],
  postMessages: [
    'Run `flutter pub get`',
    'Run `flutter run` to launch the app',
    'Architecture: Layered (UI → Providers → Services → Models)',
  ],
};
