// ─────────────────────────────────────────────────────────
// Laravel Templates — MVC, Layered, Modular Monolith
// PHP + Laravel
// ─────────────────────────────────────────────────────────

import { TemplateManifest } from '../types';

// ── Shared files ────────────────────────────────────────

const composerJson = {
  path: 'composer.json',
  content: `{
  "name": "<%= projectName %>/<%= projectName %>",
  "type": "project",
  "description": "<%= projectName %> — generated by ArchForge",
  "require": {
    "php": "^8.3",
    "laravel/framework": "^12.0"<% if (auth === 'jwt') { %>,
    "tymon/jwt-auth": "^2.1"<% } %>
  },
  "require-dev": {
    "phpunit/phpunit": "^11.0",
    "laravel/pint": "^1.18"
  },
  "autoload": {
    "psr-4": {
      "App\\\\": "app/"
    }
  },
  "scripts": {
    "test": "phpunit",
    "lint": "pint"
  }
}
`,
};

const envFile = {
  path: '.env',
  content: `APP_NAME=<%= projectName %>
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost:<%= port %>

<% if (database === 'postgresql') { %>DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=<%= projectName %>
DB_USERNAME=postgres
DB_PASSWORD=postgres
<% } else if (database === 'mysql') { %>DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=<%= projectName %>
DB_USERNAME=root
DB_PASSWORD=
<% } else { %>DB_CONNECTION=sqlite
DB_DATABASE=database/database.sqlite
<% } %>`,
};

const gitignore = {
  path: '.gitignore',
  content: `/vendor
/node_modules
.env
*.log
/storage/framework/cache/*
/storage/framework/sessions/*
/storage/framework/views/*
`,
};

const routesApi = {
  path: 'routes/api.php',
  content: `<?php

use Illuminate\\Support\\Facades\\Route;
use App\\Http\\Controllers\\UserController;

Route::apiResource('users', UserController::class);

Route::get('/health', function () {
    return response()->json(['status' => 'ok']);
});
`,
};

// ── MVC Architecture ────────────────────────────────────

export const laravelMVCManifest: TemplateManifest = {
  stack: 'laravel',
  architecture: 'mvc',
  files: [
    composerJson,
    envFile,
    gitignore,
    routesApi,
    {
      path: 'app/Models/User.php',
      content: `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Model;

class User extends Model
{
    protected $fillable = ['name', 'email'];

    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
}
`,
    },
    {
      path: 'app/Http/Controllers/UserController.php',
      content: `<?php

namespace App\\Http\\Controllers;

use App\\Models\\User;
use Illuminate\\Http\\Request;
use Illuminate\\Http\\JsonResponse;

class UserController extends Controller
{
    public function index(): JsonResponse
    {
        return response()->json(User::all());
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users',
        ]);

        $user = User::create($validated);
        return response()->json($user, 201);
    }

    public function show(User $user): JsonResponse
    {
        return response()->json($user);
    }

    public function update(Request $request, User $user): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'sometimes|string|max:255',
            'email' => 'sometimes|email|unique:users,email,' . $user->id,
        ]);

        $user->update($validated);
        return response()->json($user);
    }

    public function destroy(User $user): JsonResponse
    {
        $user->delete();
        return response()->json(null, 204);
    }
}
`,
    },
    {
      path: 'database/migrations/0001_create_users_table.php',
      content: `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
`,
    },
  ],
  postMessages: [
    'Run `composer install`',
    'Run `php artisan key:generate`',
    'Run `php artisan migrate`',
    'Run `php artisan serve`',
    'Architecture: MVC (Models → Views → Controllers)',
  ],
};

// ── Layered Architecture ────────────────────────────────

export const laravelLayeredManifest: TemplateManifest = {
  stack: 'laravel',
  architecture: 'layered',
  files: [
    composerJson,
    envFile,
    gitignore,
    routesApi,
    {
      path: 'app/Models/User.php',
      content: `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Model;

class User extends Model
{
    protected $fillable = ['name', 'email'];
}
`,
    },
    {
      path: 'app/Repositories/UserRepository.php',
      content: `<?php

namespace App\\Repositories;

use App\\Models\\User;
use Illuminate\\Database\\Eloquent\\Collection;

class UserRepository
{
    public function findAll(): Collection
    {
        return User::all();
    }

    public function findById(int $id): ?User
    {
        return User::find($id);
    }

    public function create(array $data): User
    {
        return User::create($data);
    }

    public function update(User $user, array $data): User
    {
        $user->update($data);
        return $user->fresh();
    }

    public function delete(User $user): void
    {
        $user->delete();
    }
}
`,
    },
    {
      path: 'app/Services/UserService.php',
      content: `<?php

namespace App\\Services;

use App\\Repositories\\UserRepository;
use App\\Models\\User;
use Illuminate\\Database\\Eloquent\\Collection;

class UserService
{
    public function __construct(
        private readonly UserRepository $repository
    ) {}

    public function getAllUsers(): Collection
    {
        return $this->repository->findAll();
    }

    public function createUser(array $data): User
    {
        return $this->repository->create($data);
    }

    public function getUserById(int $id): ?User
    {
        return $this->repository->findById($id);
    }
}
`,
    },
    {
      path: 'app/Http/Controllers/UserController.php',
      content: `<?php

namespace App\\Http\\Controllers;

use App\\Services\\UserService;
use Illuminate\\Http\\Request;
use Illuminate\\Http\\JsonResponse;

class UserController extends Controller
{
    public function __construct(
        private readonly UserService $userService
    ) {}

    public function index(): JsonResponse
    {
        return response()->json($this->userService->getAllUsers());
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users',
        ]);

        $user = $this->userService->createUser($validated);
        return response()->json($user, 201);
    }

    public function show(int $id): JsonResponse
    {
        $user = $this->userService->getUserById($id);
        if (!$user) {
            return response()->json(['error' => 'Not found'], 404);
        }
        return response()->json($user);
    }
}
`,
    },
    {
      path: 'database/migrations/0001_create_users_table.php',
      content: `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
`,
    },
  ],
  postMessages: [
    'Run `composer install && php artisan key:generate`',
    'Run `php artisan migrate && php artisan serve`',
    'Architecture: Layered (Controllers → Services → Repositories → Models)',
  ],
};

// ── Modular Monolith ────────────────────────────────────

export const laravelModularMonolithManifest: TemplateManifest = {
  stack: 'laravel',
  architecture: 'modular-monolith',
  files: [
    composerJson,
    envFile,
    gitignore,
    {
      path: 'routes/api.php',
      content: `<?php

use Illuminate\\Support\\Facades\\Route;

// Module routes are registered via service providers
Route::get('/health', fn () => response()->json(['status' => 'ok']));
`,
    },
    {
      path: 'app/Modules/Users/Providers/UsersServiceProvider.php',
      content: `<?php

namespace App\\Modules\\Users\\Providers;

use Illuminate\\Support\\ServiceProvider;
use Illuminate\\Support\\Facades\\Route;

class UsersServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Route::prefix('api/users')
            ->middleware('api')
            ->group(__DIR__ . '/../Routes/api.php');
    }
}
`,
    },
    {
      path: 'app/Modules/Users/Routes/api.php',
      content: `<?php

use Illuminate\\Support\\Facades\\Route;
use App\\Modules\\Users\\Controllers\\UserController;

Route::get('/', [UserController::class, 'index']);
Route::post('/', [UserController::class, 'store']);
`,
    },
    {
      path: 'app/Modules/Users/Controllers/UserController.php',
      content: `<?php

namespace App\\Modules\\Users\\Controllers;

use App\\Http\\Controllers\\Controller;
use App\\Modules\\Users\\Services\\UserService;
use Illuminate\\Http\\Request;
use Illuminate\\Http\\JsonResponse;

class UserController extends Controller
{
    public function __construct(
        private readonly UserService $userService
    ) {}

    public function index(): JsonResponse
    {
        return response()->json($this->userService->getAll());
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'required|string',
            'email' => 'required|email|unique:users',
        ]);
        $user = $this->userService->create($validated);
        return response()->json($user, 201);
    }
}
`,
    },
    {
      path: 'app/Modules/Users/Models/User.php',
      content: `<?php

namespace App\\Modules\\Users\\Models;

use Illuminate\\Database\\Eloquent\\Model;

class User extends Model
{
    protected $fillable = ['name', 'email'];
}
`,
    },
    {
      path: 'app/Modules/Users/Services/UserService.php',
      content: `<?php

namespace App\\Modules\\Users\\Services;

use App\\Modules\\Users\\Models\\User;

class UserService
{
    public function getAll()
    {
        return User::all();
    }

    public function create(array $data): User
    {
        return User::create($data);
    }
}
`,
    },
    {
      path: 'app/Modules/Orders/Providers/OrdersServiceProvider.php',
      content: `<?php

namespace App\\Modules\\Orders\\Providers;

use Illuminate\\Support\\ServiceProvider;
use Illuminate\\Support\\Facades\\Route;

class OrdersServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Route::prefix('api/orders')
            ->middleware('api')
            ->group(__DIR__ . '/../Routes/api.php');
    }
}
`,
    },
    {
      path: 'app/Modules/Orders/Routes/api.php',
      content: `<?php

use Illuminate\\Support\\Facades\\Route;

Route::get('/', fn () => response()->json([]));
`,
    },
    {
      path: 'database/migrations/0001_create_users_table.php',
      content: `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
`,
    },
  ],
  postMessages: [
    'Run `composer install && php artisan key:generate`',
    'Register module service providers in config/app.php',
    'Run `php artisan migrate && php artisan serve`',
    'Architecture: Modular Monolith (isolated modules with service providers)',
  ],
};
