// ─────────────────────────────────────────────────────────
// Next.js Templates — Feature-Based, Feature-Sliced
// Next.js 15 + TypeScript + App Router
// ─────────────────────────────────────────────────────────

import { TemplateManifest } from '../types';

// ── Shared files ────────────────────────────────────────

const packageJson = {
  path: 'package.json',
  content: `{
  "name": "<%= projectName %>",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --port <%= port %>",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test": "vitest"
  },
  "dependencies": {
    "next": "^15.3.3",
    "react": "^19.1.0",
    "react-dom": "^19.1.0"<% if (stateManagement === 'zustand') { %>,
    "zustand": "^5.0.5"<% } else if (stateManagement === 'redux') { %>,
    "@reduxjs/toolkit": "^2.8.2",
    "react-redux": "^9.2.0"<% } %><% if (validation === 'zod') { %>,
    "zod": "^4.0.0"<% } %><% if (cssFramework === 'tailwind') { %>,
    "tailwindcss": "^4.1.8",
    "@tailwindcss/postcss": "^4.1.8"<% } %>
  },
  "devDependencies": {
    "typescript": "^5.9.0-beta",
    "@types/react": "^19.1.4",
    "@types/react-dom": "^19.1.5",
    "vitest": "^3.1.4",
    "@testing-library/react": "^16.3.0",
    "eslint": "^9.28.0",
    "eslint-config-next": "^15.3.3"
  }
}
`,
};

const tsconfig = {
  path: 'tsconfig.json',
  content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "jsx": "preserve",
    "module": "esnext",
    "moduleResolution": "bundler",
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "paths": {
      "@/*": ["./src/*"]
    },
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
};

const nextConfig = {
  path: 'next.config.ts',
  content: `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`,
};

const envFile = {
  path: '.env.local',
  content: `<% if (database === 'postgresql') { %>DATABASE_URL=postgresql://postgres:postgres@localhost:5432/<%= projectName %>
<% } else if (database === 'mysql') { %>DATABASE_URL=mysql://root:@localhost:3306/<%= projectName %>
<% } else if (database === 'mongodb') { %>DATABASE_URL=mongodb://localhost:27017/<%= projectName %>
<% } %>PORT=<%= port %>
`,
};

const gitignore = {
  path: '.gitignore',
  content: `node_modules/
.next/
out/
dist/
.env*.local
*.tsbuildinfo
`,
};

const layoutFile = {
  path: 'src/app/layout.tsx',
  content: `<% if (cssFramework === 'tailwind') { %>import './globals.css';<% } %>
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '<%= projectName %>',
  description: 'Generated by ArchForge',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
};

const globalsCss = {
  path: 'src/app/globals.css',
  content: `<% if (cssFramework === 'tailwind') { %>@import "tailwindcss";
<% } else { %>* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui, sans-serif; }
<% } %>`,
};

// ── Feature-Based Architecture ──────────────────────────

export const nextjsFeatureBasedManifest: TemplateManifest = {
  stack: 'nextjs',
  architecture: 'feature-based',
  files: [
    packageJson,
    tsconfig,
    nextConfig,
    envFile,
    gitignore,
    layoutFile,
    globalsCss,
    {
      path: 'src/app/page.tsx',
      content: `export default function HomePage() {
  return (
    <main>
      <h1><%= projectName %></h1>
      <p>Feature-Based Architecture — Next.js App Router</p>
    </main>
  );
}
`,
    },
    {
      path: 'src/features/users/components/UserList.tsx',
      content: `'use client';

import { useUsers } from '../hooks/useUsers';

export function UserList() {
  const { users, isLoading } = useUsers();

  if (isLoading) return <p>Loading...</p>;

  return (
    <ul>
      {users.map((u) => (
        <li key={u.id}>{u.name}</li>
      ))}
    </ul>
  );
}
`,
    },
    {
      path: 'src/features/users/hooks/useUsers.ts',
      content: `'use client';

import { useState, useEffect } from 'react';
import type { User } from '../types';

export function useUsers() {
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetch('/api/users')
      .then((res) => res.json())
      .then((data) => {
        setUsers(data);
        setIsLoading(false);
      });
  }, []);

  return { users, isLoading };
}
`,
    },
    {
      path: 'src/features/users/types.ts',
      content: `export interface User {
  id: string;
  name: string;
  email: string;
}
`,
    },
    {
      path: 'src/features/users/actions/userActions.ts',
      content: `'use server';

export async function getUsers() {
  // Replace with real data source
  return [
    { id: '1', name: 'Alice', email: 'alice@example.com' },
  ];
}

export async function createUser(formData: FormData) {
  const name = formData.get('name') as string;
  const email = formData.get('email') as string;
  // Persist user
  return { id: crypto.randomUUID(), name, email };
}
`,
    },
    {
      path: 'src/app/api/users/route.ts',
      content: `import { NextResponse } from 'next/server';

const users = [
  { id: '1', name: 'Alice', email: 'alice@example.com' },
];

export async function GET() {
  return NextResponse.json(users);
}

export async function POST(request: Request) {
  const body = await request.json();
  const user = { id: crypto.randomUUID(), ...body };
  users.push(user);
  return NextResponse.json(user, { status: 201 });
}
`,
    },
    {
      path: 'src/shared/components/Button.tsx',
      content: `interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary';
}

export function Button({ variant = 'primary', children, ...props }: ButtonProps) {
  return (
    <button data-variant={variant} {...props}>
      {children}
    </button>
  );
}
`,
    },
  ],
  postMessages: [
    'Run `<%= packageManager %> install`',
    'Run `<%= packageManager %> run dev` to start on port <%= port %>',
    'Architecture: Feature-Based (features/ contain components, hooks, types, actions)',
  ],
};

// ── Feature-Sliced Architecture ─────────────────────────

export const nextjsFeatureSlicedManifest: TemplateManifest = {
  stack: 'nextjs',
  architecture: 'feature-sliced',
  files: [
    packageJson,
    tsconfig,
    nextConfig,
    envFile,
    gitignore,
    layoutFile,
    globalsCss,
    {
      path: 'src/app/page.tsx',
      content: `import { UserList } from '@/widgets/user-list/ui/UserList';

export default function HomePage() {
  return (
    <main>
      <h1><%= projectName %></h1>
      <UserList />
    </main>
  );
}
`,
    },
    // ── Shared layer
    {
      path: 'src/shared/ui/Button.tsx',
      content: `interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary';
}

export function Button({ variant = 'primary', children, ...props }: ButtonProps) {
  return <button data-variant={variant} {...props}>{children}</button>;
}
`,
    },
    {
      path: 'src/shared/api/client.ts',
      content: `export async function apiClient<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(\`API error: \${res.status}\`);
  return res.json();
}
`,
    },
    // ── Entities layer
    {
      path: 'src/entities/user/model/types.ts',
      content: `export interface User {
  id: string;
  name: string;
  email: string;
}
`,
    },
    {
      path: 'src/entities/user/api/userApi.ts',
      content: `import { apiClient } from '@/shared/api/client';
import type { User } from '../model/types';

export const userApi = {
  getAll: () => apiClient<User[]>('/api/users'),
  create: (data: Omit<User, 'id'>) =>
    apiClient<User>('/api/users', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    }),
};
`,
    },
    // ── Features layer
    {
      path: 'src/features/create-user/ui/CreateUserForm.tsx',
      content: `'use client';

import { useState } from 'react';
import { userApi } from '@/entities/user/api/userApi';
import { Button } from '@/shared/ui/Button';

export function CreateUserForm({ onCreated }: { onCreated?: () => void }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await userApi.create({ name, email });
    setName('');
    setEmail('');
    onCreated?.();
  };

  return (
    <form onSubmit={handleSubmit}>
      <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" />
      <input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" />
      <Button type="submit">Create</Button>
    </form>
  );
}
`,
    },
    // ── Widgets layer
    {
      path: 'src/widgets/user-list/ui/UserList.tsx',
      content: `'use client';

import { useEffect, useState } from 'react';
import { userApi } from '@/entities/user/api/userApi';
import type { User } from '@/entities/user/model/types';

export function UserList() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    userApi.getAll().then(setUsers);
  }, []);

  return (
    <ul>
      {users.map((u) => (
        <li key={u.id}>{u.name} — {u.email}</li>
      ))}
    </ul>
  );
}
`,
    },
    // ── API route
    {
      path: 'src/app/api/users/route.ts',
      content: `import { NextResponse } from 'next/server';

const users = [{ id: '1', name: 'Alice', email: 'alice@example.com' }];

export async function GET() {
  return NextResponse.json(users);
}

export async function POST(request: Request) {
  const body = await request.json();
  const user = { id: crypto.randomUUID(), ...body };
  users.push(user);
  return NextResponse.json(user, { status: 201 });
}
`,
    },
  ],
  postMessages: [
    'Run `<%= packageManager %> install`',
    'Run `<%= packageManager %> run dev` to start on port <%= port %>',
    'Architecture: Feature-Sliced Design (shared → entities → features → widgets → app)',
  ],
};
